### ISSUE TITLE
[Feature Request] Backport "Allow Inventory Key to close" GUI functionality to Fabric 1.16.1

### ISSUE THREAD

**Issue by Abbanon** [gbl/Beenfo#10]
I'm the user who initially requested the "Press Inv. Key to close" option in the CurseForge comments [here](https://www.curseforge.com/minecraft/mc-mods/beenfo?comment=50).

As of right now, the 1.16.2 and 1.16.3 versions of the mod **do** work with 1.16.1, but the game crashes whenever you try to access the GUI of a beehive/bee nest that has a **named bee** inside of it.

So I'm curious, would you be willing to backport the GUI close functionality to a 1.16.1-friendly mod version, such as 
`beenfo-1.16-fabric0.13.1-1.1.1.jar`?

**Comment by gbl** [comment]
Done and uploaded to CF. It's beenfo-1.16-fabric0.13.1-1.2.jar as I named the Beenfo version that has it 1.2.
