### ISSUE TITLE
Mod config screen seems to be visually bugged?

### ISSUE THREAD

**Issue by Abbanon** [gbl/Beenfo#13]
Notice the sliders and the boxes on the right. Are they intended to appear like this?
*(Using the latest stable Fabric release: **beenfo-1.16.4-fabric0.25.1-1.3.jar**)*
![2021-01-16_01 07 35](https://user-images.githubusercontent.com/37251822/104807062-ca4c0000-57a9-11eb-986e-e7bd0bfcb948.png)

**Comment by gbl** [comment]
Yes. The small buttons to the right reset the sliders/button to their default value.
