### ISSUE TITLE
Sometimes crashes on secondary click

### ISSUE THREAD

**Issue by AestheticSkye** [gbl/Beenfo#16]
[crash-2021-05-02_18.31.22-client.txt](https://github.com/gbl/Beenfo/files/6411044/crash-2021-05-02_18.31.22-client.txt)

**Comment by ArtiTice** [comment]
+1 Righting clicking on bee hive causes freezes/crashes sometimes.

**Comment by gbl** [comment]
I wasn't able to reproduce this myself, it seems to happen under some very specific circumstances  only. Can you tell me a bit more (are you playing single player, or on a Fabric server, or on a Spigot/Paper server? Does it only happen when you're holding a specific item in your hand?)

I made a version that logs a bit more what's happening where; could you try this:  https://github.com/gbl/Beenfo/releases/tag/1.3.1-debug
and send me a crash log of that if it happens again? Thanks.

**Comment by ArtiTice** [comment]
Sure, I was playing on my modded Fabric server and right clicked on the bee hive with nothing in my hand. It either freezes sometimes or it crashes my Minecraft client sometimes. I do have a lot of other mods installed. I'll provide a generated mod list. I will also install the debug version and let you know if it happens again and provide my crash log. 
[modlist.txt](https://github.com/gbl/Beenfo/files/6651603/modlist.txt)

**Comment by ArtiTice** [comment]
Also just realized upon crash that the debug version you gave me was 1.17. Can you provide the 1.16.5 version? 
Thanks

**Comment by gbl** [comment]
Oh wow! When I backported the debug stuff to 1.16.5, I noticed I had fixed a bug with opening the screen in 20w49a, but that fix never made it back to 1.16.5. I repaired that now, and just uploaded a beenfo-1.16.5-fabric0.30.0-1.3.1.jar to CurseForge and Modrinth. Quite certain you won't have the bug any more if you use that version.

**Comment by ArtiTice** [comment]
Nice, I'll let you know if I happen to encounter any more issues with the newest version.

**Comment by ArtiTice** [comment]
Seems the newest beenfo version(1.3.1) causes my server to crash. On the client it runs fine. Here is the server output log right before it crashed. 
[Server Output.txt](https://github.com/gbl/Beenfo/files/6659112/Server.Output.txt)

**Comment by gbl** [comment]
Unfortunately, you're right, seems a fix I made at some point didn't make it into the 1.3.1 version - this happens when you try to keep 1.16 fabric, 1.16 forge and 1.17 fabric in sync. Fortunately, your old version on the server and the new version on the client should be able to work together.
Anyway, I just released a 1.3.2 version, which hopefully works everywhere.
