### ISSUE TITLE
Mod installed on server + client, right-click GUI only works on "op" status

### ISSUE THREAD

**Issue by Abbanon** [gbl/Beenfo#17]
As the issue name implies, we have this mod installed on a Fabric server, and all of the clients have the mod as well.
For some reason, you can only view the right-click GUI for hives/nests when you have "op" status. 
Players who aren't opped can't right-click view. Is this a bug, or an intended feature? 
Because being able to let non-opped players right-click view hives/nests is ideal in our scenario.

Edit:
I forgot to mention, we're running Fabric 1.16.5, with the latest mod file available for that version.

**Comment by gbl** [comment]
That's not intended; it should work normally.

Do you have some other mod installted that prevents opening communication channels between server and client if the client isn't opped? Some kind of permission plugin or whatever? Or some mod that prevents using some kind of items on some kind of blocks? Beenfo detects item uses if they aren't handled by MC itself first (to prevents shears/bottles from opening the GUI), maybe some permission mod intercepts that to say "can't use item X on a hive" so Beenfo never gets informed?
