### ISSUE TITLE
Strange incompatability with Xaero's BetterPvP mod

### ISSUE THREAD

**Issue by Abbanon** [gbl/Beenfo#18]
Basically, it works like this:
If you have Xaero BetterPvP's "Potion Status" set to On/Enabled, it prevents Beenfo's "crosshair popup" from displaying when also On/Enabled.

Disabling BetterPvP's "Potion Status" allows Beenfo's "crossbar popup" to display just fine.

Is this something to do with Beenfo, or should I reach out to Xaero and see if it's because of their mod instead?

**Comment by gbl** [comment]
Unfortunately, it seems like Xaero's BetterPvP Source code isn't available, so I can't check what's going on. I assume that he does something like "when I paint something, stop Minecraft from painting stuff itself", which also stops Beenfo from displaying the crosshair popup. You need to ask him; I can't check any incompatibilities without access to his source code.

**Comment by Abbanon** [comment]
I reached out to Xaero, and this was their response:

> Thanks for letting me know!
> Unfortunately, I can't really fix it on my end without creating more compatibility issues with other mods. I'm cancelling the vanilla potion effects rendering to render my own HUD later instead, and Beenfo renders theirs inside the renderStatusEffectOverlay method, which is cancelled by my mod. So they'll have to work around it on their end.

So do you think this issue could be re-opened, in the very least as a reference for possible future compatibility?
