### ISSUE TITLE
Annoying server message

### ISSUE THREAD

**Issue by ghost** [gbl/Beenfo#24]
Hello, it would be nice if you could fix that. It's not  important, just annoying.

[main/WARN]: Warnings were found!
- Mod 'Beenfo' (beenfo) 1.19-fabric0.53.3-1.3.3 recommends any version of modmenu, which is missing!
- You should install any version of modmenu for the optimal experience.

**Comment by gbl** [comment]
Sorry, won't/can't fix that. On the client, using ModMenu is a good idea because it'll help you get to the config screen. So the recommendation is there on purpose. But I can't make a recommendation "client only", so it'll also be there on a dedicated server.

**Comment by ghost** [comment]
Oki, thank you for the fast answer!

**Comment by gbl** [comment]
I guess if it really bothers you, you can open the jar with a zip viewer, edit the fabric.mod.json file in there, and remove the "recommends" entry. But you'll have to do this again whenever you update.
