### ISSUE TITLE
Crash on right-click, Forge 41.0.100, Beeinfo 41.0.17-1.2

### ISSUE THREAD

**Issue by jwrichards1982** [gbl/Beenfo#26]
No other mods, clean config directory, new world.
Right click to place an item and game immediately crashes.
This is any item/block on any surface/block
[crash-2022-07-19_16.34.53-client.txt](https://github.com/gbl/Beenfo/files/9145303/crash-2022-07-19_16.34.53-client.txt)
[debug.log](https://github.com/gbl/Beenfo/files/9145306/debug.log)
[latest.log](https://github.com/gbl/Beenfo/files/9145307/latest.log)

**Comment by DancerVlt69** [comment]
Same with Forge 41.1.0 by clicking right (on any storage block with or without anything in main/off hand):

> *java.lang.NoSuchMethodError: 'net.minecraft.world.level.Level net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock.getWorld()'*

[crash-2022-07-27_20.49.18-client.txt](https://github.com/gbl/Beenfo/files/9202839/crash-2022-07-27_20.49.18-client.txt)
[debug.log](https://github.com/gbl/Beenfo/files/9202855/debug.log)
[latest.log](https://github.com/gbl/Beenfo/files/9202856/latest.log)
