### ISSUE TITLE
Crosshair popup not showing bee count

### ISSUE THREAD

**Issue by azhippy** [gbl/Beenfo#27]
Minecraft 1.19.1
Beenfo mod v1.19.1-fabric0.58.5-1.3.3
Fabric loader 0.14.8
Fabric API 0.58.5+1.19.1
Sodium 0.4.2+build 16

Settings:
Left to right: 50
Top to down: 50
Show crosshair popup: True

Crosshair popup does not show bees in hive or nest. Bee count displays correctly while mousing over in inventory. 

Honey count shows correctly with popup as well as in inventory.

**Comment by gbl** [comment]
Hm, I just verified that config to work for me.

![image](https://user-images.githubusercontent.com/243563/182598931-dfb9b7fe-822e-4959-b328-772a8fc96e86.png)


Are you playing locally, or on a server? If you're on a server, the inventory popup will work, but the crosshair popup, and the right-click-a-nest feature need the mod to be installed on the server as well.
You also can't be too far from the nest; the popup will only work as long as the "looking at" element of the F3 debug screen shows you're looking at the nest (or hive).

**Comment by azhippy** [comment]
I am on a server. Went back and read the description on the mod page where it states the server needs the mod as well. Apologies for opening this ticket when the answer was already on the description page.
