### ISSUE TITLE
Compatibility With Realistic Bees (Mod By Serium)

### ISSUE THREAD

**Issue by AmyRose1288** [gbl/Beenfo#35]
While using beenfo With Realistic Bees,beenfo's UI is not displayed correctly (UI goes overlapping)
![2023-08-29_15 28 34](https://github.com/gbl/Beenfo/assets/19208524/868bab43-02d9-45fc-b70b-ed4a62c4a6b6)
![2023-08-29_15 28 38](https://github.com/gbl/Beenfo/assets/19208524/651b995f-36b7-4f56-b50a-08ed97971bab)
![2023-08-29_15 29 29](https://github.com/gbl/Beenfo/assets/19208524/70a763d2-31e3-4178-ac25-e118c930b240)

Link to Realistic Bees:https://www.curseforge.com/minecraft/mc-mods/realistic-bees

**Comment by gbl** [comment]
I made an experimental version that shows as many bees as possible and a "XXX bees not shown" line below, could you check if that works for you?
(And if it does, head over to https://crowdin.com/project/beenfo and do a chinese translation?)
[beenfo-many-bees.zip](https://github.com/gbl/Beenfo/files/12464185/beenfo-many-bees.zip)

**Comment by AmyRose1288** [comment]
![2023-08-29_22 08 04](https://github.com/gbl/Beenfo/assets/19208524/4e077734-afc3-4074-9551-32f9e1ae7ac4)

it works,will do the translate as soon as possible (it's late night in china)
