### ISSUE TITLE
Issue during server startup Forge/Minecraft 1.15.2

### ISSUE THREAD

**Issue by P-rox-y** [gbl/Beenfo#4]
Hey there,

I'm getting the following on server startup on Forge/Minecraft 1.15.2 which I've listed below. 

I've also attached the crashlog to this entry.

Thank you for taking the time to create this mod!  

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Beenfo (beenfo) encountered an error during the common_setup event phase
§7net/minecraft/client/util/ITooltipFlag
]

[crash-2020-02-08_14.13.17-server.txt](https://github.com/gbl/Beenfo/files/4175106/crash-2020-02-08_14.13.17-server.txt)

**Comment by gbl** [comment]
Oh. Seems I made a mistake, the mod is supposed to be client side only, so it crashes when initializing on the server. It shouldn't do this, but in the meantime, installing it on the client only should fix the problem.
