### ISSUE TITLE
This mod overwrites the default resource pack logo with the Beenfo logo

### ISSUE THREAD

**Issue by ignamiranda** [gbl/Beenfo#5]
As seen in the right column ![image](https://user-images.githubusercontent.com/34501347/75127701-6fed1100-56b8-11ea-824a-2eb1449bbf2a.png)

**Comment by gbl** [comment]
Interesting. It doesn't do that for me, see here:

https://i.imgur.com/BG2JKtD.mp4

Can you post a list of all mods you're using? I'm especially interested in the version of the fabric mod loader, fabric mod itself, and modmenu if you'e using it.

**Comment by ignamiranda** [comment]
Fabric Loader: 0.7.6+build.181
Fabric API:  0.4.29+build.290-1.15
Mod Menu: 1.8.5+build.23

I have a lot of mods.
![image](https://user-images.githubusercontent.com/34501347/75194357-dffaa600-574f-11ea-8a45-569e78f025b0.png)

**Comment by gbl** [comment]
New versions renamed the logo from pack.png to icon.png so this shouldn't happen any more, even though I don't understand how that was a problem in the first place.
